#include <stdio.h>

/* 
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 * By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
 * find the sum of the even-valued terms.
 *
*/
int main()
{
    int prev_1 = 0;
    int prev_2 = 0;
    int current = 1;
    int total = 0;

    do {
        prev_2 = prev_1;
        prev_1 = current;
        current = prev_1 + prev_2;
        if (current % 2 == 0)
            total += current;
    } while (current < 4000000);

    printf("%d\n", total);
    
    return 0;
}
